version: '2'

## DEVELOPERS DOCKER COMPOSE NOT FOR THE END-USER ##
##
## Build order: `docker-compose build` (does not matter)
## docker-compose build mysql
## docker-compose build proxy
## docker-compose build solr
## docker-compose build fedora
## docker-compose build apache
##
## Run order: `docker-compose up -d proxy` (if you want to watch proxy, remove -d this remains attached to proxy for testing - you will see ALL logs as stdin/stderr.)
##
## To Test Images using the built-in ISLE.LOCALDOMAIN SITE: `docker exec -it isle-apache bash` `cd /tmp` `./install_isle_ld_site.sh`
## Please note: ^ this data will not be pushed or included in Dockerhub. Creating a Drupal site falls to the enduser or developer and is not part of the Docker image build process.
##
## DEVELOPERS DOCKER COMPOSE NOT FOR THE END-USER ##

services:
  mysql:
    build:
      context: ./mysql
    image: islandoracollabgroup/isle-mysql:latest
    container_name: isle-mysql-ld
    environment:
      - MYSQL_ROOT_PASSWORD=ild_mysqlrt_2018
    networks:
      - isle-internal
    ports:
      - "3306:3306"
    volumes:
      - db-data-ld:/var/lib/mysql
      - ./data/mysql/log:/var/log/mysql

  fedora:
    build:
      context: ./fedora
    image: islandoracollabgroup/isle-fedora:latest
    container_name: isle-fedora-ld
    networks:
      - isle-internal
    ports:
      - "8080:8080"
    tty: true
    depends_on:
      - mysql
      - solr
    volumes:
      - fed-data-ld:/usr/local/fedora/data
      - ./data/fedora/log/fedora:/usr/local/fedora/server/logs
      - ./data/fedora/log/tomcat:/usr/local/tomcat/logs

  solr:
    build:
      context: ./solr
    image: islandoracollabgroup/isle-solr:latest
    container_name: isle-solr-ld
    networks:
      - isle-internal
    ports:
      - "8091:8080"
    tty: true
    depends_on:
      - mysql
    volumes:
      - solr-data-ld:/usr/local/solr/collection1/data
      - ./data/solr/logs:/usr/local/tomcat/logs

  apache:
    build:
      context: ./apache
    image: islandoracollabgroup/isle-apache:latest
    container_name: isle-apache-ld
    networks:
      isle-internal:
        aliases:
          - isle.localdomain
    tty: true
    depends_on:
      - mysql
      - fedora
      - solr
    volumes:
      - apache-data-ld:/var/www/html
      - ./data/apache/log/apache:/var/log/apache2

  proxy:
    build:
      context: ./proxy
    image: islandoracollabgroup/isle-proxy:latest
    container_name: isle-proxy
    networks:
      isle-internal:
      isle-external:
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - mysql
      - fedora
      - solr
      - apache
    command: [nginx-debug, '-g', 'daemon off;']


# Defined networks
networks:
  isle-internal:
  isle-external:

volumes:
  db-data-ld:
  fed-data-ld:
  solr-data-ld:
  apache-data-ld:
