version: '2'
labels:
  org.label-schema.version: "ISLE Alpha 2.0"
  org.label-schema.description: "ISLE Base Image with sample site isle.localdomain docker-compose.yml for non-production usage."
  org.label-schema.license: "Apache-2.0"
  org.label-schema.vcs-url: "git@github.com:Islandora-Collaboration-Group/ISLE.git"
  org.label-schema.vendor: "Islandora Collaboration Group (ICG) - islandora-consortium-group@googlegroups.com"
  org.label-schema.schema-version: "1.0"

services:
  mysql:
    build: ./mysql
    image: islandoracollabgroup/isle-mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=ild_mysqlrt_2018
    ports:
      - "3306:3306"
    volumes:
      - ild_mysql_data:/var/lib/mysql
      - ild_mysql_logs:/var/log/mysql
    container_name: isle-mysql

  fedora:
    build: ./fedora
    image: islandoracollabgroup/isle-fedora:latest
    ports:
      - "8080:8080"
      - "8777:80"
    tty: true
    depends_on:
      - mysql
    volumes:
    - ild_fedora_data:/usr/local/fedora/data
    - ild_fedora_logs:/usr/local/fedora/server/logs
    - ild_fedora_apache_logs:/var/log/apache2
    - ild_fedora_tomcat_logs:/usr/local/tomcat/logs
    container_name: isle-fedora

  solr:
    build: ./solr
    image: islandoracollabgroup/isle-solr:latest
    ports:
      - "8091:8080"
      - "8983:8983"
    tty: true
    volumes:
    - ild_solr_data:/usr/local/solr/collection1/data
    - ild_solr_logs:/usr/local/tomcat/logs
    container_name: isle-solr

  apache:
    build: ./apache
    image: islandoracollabgroup/isle-apache:latest
    environment:
      - JAVA_HOME=/usr/lib/jvm/java-8-oracle/
      - JRE_HOME=/usr/lib/jvm/java-8-oracle/jre
      - PATH="$PATH:$HOME/.composer/vendor/bin:/usr/lib/jvm/java-8-oracle/bin:/usr/lib/jvm/java-8-oracle/jre/bin"
      - KAKADU_LIBRARY_PATH=/opt/adore-djatoka-1.1/lib/Linux-x86-64
      - KAKADU_HOME=/opt/adore-djatoka-1.1/bin/Linux-x86-64
    ports:
      - "80:80"
    tty: true
    depends_on:
      - mysql
      - fedora
    volumes:
      - isld_apache_data:/var/www/html
      - isld_apache_logs:/var/log/apache2
      #- ./isle_localdomain/macosx_settings.php:/var/www/html/sites/default/settings.php
    container_name: isle-apache

volumes:
  ild_mysql_data:
     external: true

  ild_mysql_logs:
     external: true

  ild_fedora_data:
     external: true

  ild_fedora_logs:
     external: true

  ild_fedora_apache_logs:
     external: true

  ild_fedora_tomcat_logs:
     external: true

  ild_solr_data:
     external: true

  ild_solr_logs:
     external: true

   ild_apache_data:
     external: true

   ild_apache_logs:
     external: true
