site_name: Islandora Enterprise (ISLE)
site_description: Documentation for Islandora Enterprise (ISLE)

site_dir: site
docs_dir: docs

#dev_addr: '127.0.0.1:8009'#

theme: material #readthedocs #material

extra:
  palette:
    primary: 'blue'
    accent: 'blue'
  logo:
    icon: 'account_balance'

pages:
- Home: index.md
- About: about.md

- 1. System / Process Overview:
  - '1.1 - Executive summary': '1_system_process_overview/summary.md'
  - '1.2 - MVP specs': '1_system_process_overview/mvpspecs.md'
  - '1.3 System Overview':
    - '1.3 - System overview': '1_system_process_overview/1_3_system_overview/systemoverview.md'
    - '1.3 - Supported Specification Matrix table': '1_system_process_overview/1_3_system_overview/supported-specification-matrix-table.md'
  - '1.4 - Testing':
    - '1.4 - Testing - "Sample Data"': '1_system_process_overview/1_4_testing/sampledata.md'
    - '1.4 - Testing - Travis CI': '1_system_process_overview/1_4_testing/travis-ci.md'
  - '1.5 - Alphas': '1_system_process_overview/alphas.md'

- 2. End-user guide:
  - '2.1 - Host System Requirements': '2_enduser_guide/host-requirements.md'
  - '2.2 - Usage Guide': '2_enduser_guide/usage-guide.md'
  - '2.3 Containers':
    - '2.3 Container Inventory': '2_enduser_guide/2_3_containers/containers-inventory.md'
    - '2.3 Container - Apache': '2_enduser_guide/2_3_containers/apache/containers-apache.md'
  - '2.4 - ISLE Customization Points': '2_enduser_guide/2_4_customize/customization-points.md'
  - '2.5 - ISLE Container Selection + Docker Compose Usage': '2_enduser_guide/2_5_container_selection/container-selection.md'
  - '2.6 - Data Management':
    - '2.6 - Mount Points': '2_enduser_guide/2_6_data_management/mountpoints.md'
    - '2.6 - Migrations': '2_enduser_guide/2_6_data_management/migrations.md'
    - '2.6 - Upgrations': '2_enduser_guide/2_6_data_management/upgrations.md'
  - '2.7 - Managing multiple environments':
    - '2.7 - Recommended Git structure': '2_enduser_guide/2_7_managing_multiple_environments/git-structure.md'
    - '2.7 - Data Replications and Movement': '2_enduser_guide/2_7_managing_multiple_environments/data-replications.md'
    - '2.7 - Container Movement': '2_enduser_guide/2_7_managing_multiple_environments/container-movement.md'

#- 3. ISLE developer guide for ISLE Maintainers:
- 3. ISLE developer guide for ISLE Maintainers:
  - '3.1 - Contributing to Docs': '3_dev_guide/contributing-to-docs.md'
