site_name: Islandora Enterprise (ISLE)
site_description: Documentation for Islandora Enterprise (ISLE)

site_dir: site
docs_dir: docs
extra_css: [extra.css]
extra_javascript: [extra.js]
#markdown_extensions:
#    - del_ins
theme:
  name: 'material'

extra:
  palette:
    primary: 'blue'
    accent: 'blue'
  logo:
    icon: 'account_balance'

nav:
- Get Started: index.md
- 'Install ISLE':
  - '1. Hardware Requirements': '01_installation_host_server/hardware-requirements.md'
  - '2. Software Dependencies': '01_installation_host_server/software-dependencies.md'
  - '3. Install ISLE': '02_installation_site/site_installation.md'
  - '4. Server Configurations':
    - 'Single ISLE Environment': '02_installation_site/site_installation_single.md'
    - 'Multiple ISLE Environments': '02_installation_site/site_installation_multiple.md'
- 'Update ISLE': '03_update_site/update_isle.md'
- 'Migrate Existing Site to ISLE':
  - 'Migration Installation Guide': '04_installation_migration/migration_installation_guide.md'
  - 'Migration Export Checklist': '04_installation_migration/migration_export_checklist.md'
  - 'Migration Merge Checklist': '04_installation_migration/migration_merge_checklist.md'
  - 'Migration Reindex Process': '04_installation_migration/migration_reindex_process.md'
- 'Appendices':
  - 'Demo ISLE Site Resources': '07_appendices/demo_resources.md'
  - 'Demo ISLE Site Troubleshooting': '07_appendices/demo_troubleshooting.md'
  - 'Edit the "/etc/hosts" File': '07_appendices/edit-the-hosts-file.md'
  - 'Glossary': '07_appendices/glossary.md'
  - 'Installing a Drupal Module with Composer': '07_appendices/installing-module-with-composer.md'
  - 'Installing a Drupal Module with Drush': '07_appendices/installing-module-with-drush.md'
  - 'Installing on Google Cloud Platform (Google Doc)': 'https://docs.google.com/document/d/1r-I9n8mUhlJ5Z-X9AO-RrikhzH6I8bTPIL25LmtRbxE'
  - 'Opening a Terminal in a Running Container': '07_appendices/open-terminal-in-running-container.md'
  - 'Sample IT Department Request Letter': '07_appendices/sample-it-department-request.md'
  - 'Troubleshooting': '07_appendices/install_troubleshooting.md'
  - 'User Stories':
    - 'Demo ISLE Site Example User Story': '07_appendices/user_story_demo_site.md'
    - 'New Site Example User Story': '07_appendices/user_story_new_site.md'
    - 'Migration Example User Story': '07_appendices/user_story_migration_site.md'
  - 'Using Let''s Encrypt with ISLE' : '07_appendices/configuring-lets-encrypt.md'
  - 'Warning about Installing on Red Hat': '07_appendices/redhat.md'
- 'Cookbook Recipes':
  - 'ISLE Cheat Sheet: Docker Commands': '10_cookbook_recipes/isle-cheatsheet-docker-commands.md'
- 'About':
  - 'Contributing to ISLE': '08_about/about_contributing_to_ISLE.md'
  - 'About ISLE': '08_about/about_isle.md'
  - 'About Committers': '08_about/about_maintainers.md'
  - 'Contributor Docs':
    - 'Docs: MkDocs': '05_contributor_docs/contributor_docs_mkdocs.md'
    - 'Docs: Spell Checker': '05_contributor_docs/contributor_docs_spell_checker.md'
    - 'Docs: Style Guide': '05_contributor_docs/contributor_docs_style_guide.md'
    - 'Release Process': '05_contributor_docs/contributor_release_process.md'
    - 'Testing Guide': '05_contributor_docs/contributor_testing_guide.md'
  - 'Get Help': '08_about/about_get_help.md'
- 'Release Notes': '09_release_notes/release_notes.md'
