site_name: Islandora Enterprise (ISLE)
site_description: Documentation for Islandora Enterprise (ISLE)

site_dir: site
docs_dir: docs

#dev_addr: '127.0.0.1:8009'#

theme:
  name: 'material' #mkdocs-material #readthedocs #material

extra:
  palette:
    primary: 'blue'
    accent: 'blue'
  logo:
    icon: 'account_balance'

pages:
- Home: index.md
- About: about.md
- Glossary of Terms and Variables: glossary.md
- 'Installation':
  - 'Host Server Overview': '01_installation_host_server/host_server_overview.md'
  - 'System Requirements': '01_installation_host_server/host_server_system_requirements.md'
  - 'CentOS': '01_installation_host_server/host_server_centos.md'
  - 'Ubuntu': '01_installation_host_server/host_server_ubuntu.md'
  - 'MacOS': '01_installation_host_server/host_server_macos.md'
- 'Installation - Development (isle.localdomain)':
  - 'Example User Story': '02_installation_development/ild_example_user_story.md'
  - 'Installation Guide': '02_installation_development/ild_installation_guide.md'
  - 'Resources': '02_installation_development/ild_resources.md'
- 'Installation - New Site':
  - 'Example User Story': '03_installation_new_site/new_site_example_user_story.md'
  - 'Installation Guide': '03_installation_new_site/new_site_installation_guide.md'
- 'Installation - Migration':
  - 'Example User Story': '04_installation_migration/migration_example_user_story.md'
  - 'Installation Guide': '04_installation_migration/migration_installation_guide.md'
  - 'Export Checklist': '04_installation_migration/migration_export_checklist.md'
  - 'Merge Checklist': '04_installation_migration/migration_merge_checklist.md'
  - 'Docker Composer Edit Checklist': '04_installation_migration/migration_docker_compose_edit_checklist.md'
  - 'Reindex Process': '04_installation_migration/migration_reindex_process.md'
- 'Developer Docs':
  - 'Contributing to Project': '05_developer_docs/dev_contributing_to_project.md'
  - 'Documentation Overview': '05_developer_docs/dev_documentation_overview.md'
  - 'Documentation Editing - Online': '05_developer_docs/dev_documentation_editing_online.md'
  - 'Documentation Editing - Local': '05_developer_docs/dev_documentation_editing_local.md'
  - 'Installing Mkdocs': '05_developer_docs/dev_documentation_mkdocs.md'
  - 'About Maintainers': '05_developer_docs/dev_about_maintainers.md'
  - 'About Project': '05_developer_docs/dev_about_project.md'
  - 'Release process': '05_developer_docs/dev_release_process.md'
  - 'Example User Story': '05_developer_docs/dev_example_user_story.md'
  - 'Policies': '05_developer_docs/dev_policies.md'
  - 'Build Guide': '05_developer_docs/dev_build_guide.md'
  - 'Testing Guide': '05_developer_docs/dev_testing_guide.md'
  - 'Pushing images to Dockerhub Guide': '05_developer_docs/dev_push_images_dockerhub.md'
  - 'Announcements of new releases': '05_developer_docs/dev_announcements_releases.md'
  - 'Ansible Guide': '05_developer_docs/dev_ansible_guide.md'
- 'Specifications':
  - 'Dockerfiles': '06_specifications/specs_dockerfiles.md'
  - 'Docker Images': '06_specifications/specs_docker_images.md'
  - 'Docker Containers': '06_specifications/specs_docker_containers.md'
  - 'Diagram of network and connections': '06_specifications/specs_diagram_network.md'
  - 'Supported Islandora Specification Matrix': '06_specifications/specs_supported_matrix.md'
