version: '2'
labels:
  org.label-schema.version: "Production - Enduser Institution"
  org.label-schema.description: "Enduser Institution docker-compose.yml for use with the official ISLE Dockerhub images and pre-existing production Enduser Institution configurations and data."
  org.label-schema.license: "Apache-2.0"
  org.label-schema.vcs-url: "EDIT - ISLE enduser Github repositiory information here" # edit here and remove comment e.g. org.label-schema.vcs-url: "git@github.com:Islandora-Collaboration-Group/ISLE.git"
  org.label-schema.vendor: "EDIT - ISLE enduser Institution information here" # edit here and remove comment
  org.label-schema.schema-version: "1.0"

services:
  mysql:
    image: islandoracollabgroup/isle-mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=BLAH #edit here and remove comment
      - MYSQL_DATABASE= #edit here and remove comment
      - MYSQL_USER= #edit here and remove comment
      - MYSQL_PASSWORD= #edit here and remove comment
    ports:
      - "3306:3306"
    volumes:
      - ./mysql/initscripts:/docker-entrypoint-initdb.d
      #- ./customize/mysql/my.cnf:/etc/alternatives/my.cnf #(optional - edit here and remove comment)
      - production_mysql_data:/var/lib/mysql #edit here and remove comment
      - production_mysql_log:/var/log/mysql #edit here and remove comment
    container_name: isle-mysql

  fedora:
    image: islandoracollabgroup/isle-fedora:latest
    ports:
      - "8080:8080"
      - "8443:8443"
      - "8777:80"
      - "8778:443"
    tty: true
    environment:
      - FEDORA_ADMIN_PASS= #edit here and remove comment
      - DATABASE_PASSWORD= #edit here and remove comment
    depends_on:
      - mysql
    volumes:

#consolidate to just the conf folder ?
    - ./fedora/config/production/

    - ./fedora/config/production/server.xml:/usr/local/tomcat/conf/server.xml
    - ./fedora/config/production/tomcat/web.xml:/usr/local/tomcat/conf/web.xml
    - ./fedora/config/production/tomcat/tomcat-users.xml:/usr/local/tomcat/conf/tomcat-users.xml
    #- ./fedora/config/production/tomcat/logging.properties:/usr/local/tomcat/conf/logging.properties
    - ./fedora/config/production/fedora/repository-policies/default:/usr/local/fedora/data/fedora-xacml-policies/repository-policies/default
    - ./fedora/config/production/fedora/repository-policies/islandora:/usr/local/fedora/data/fedora-xacml-policies/repository-policies/islandora

#consolidate to just the config folder ?
    - ./fedora/config/production/fedora/fedora-users.xml:/usr/local/fedora/server/config/fedora-users.xml
    - ./customize/fedora/fedora/logback.xml:/usr/local/fedora/server/config/logback.xml
    - ./customize/fedora/drupalfilter/filter-drupal.xml:/usr/local/fedora/server/config/filter-drupal.xml

    #- ./customize/fedora/adore-djatoka/index.html:/usr/local/tomcat/webapps/adore-djatoka/index.html
    #- ./customize/fedora/adore-djatoka/log4j.properties:/usr/local/tomcat/webapps/adore-djatoka/WEB-INF/classes/log4j.properties #(optional)edit here and remove comment
    - ./customize/fedora/apache/site.conf:/etc/apache2/sites-available/site.conf
    - ./customize/fedora/gsearch/index.properties:/usr/local/tomcat/webapps/fedoragsearch/WEB-INF/classes/fgsconfigFinal/index/FgsIndex/index.properties

    - ./data/fedora/data:/usr/local/fedora/data
    - ./data/fedora/log/fedora:/usr/local/fedora/server/logs
    - ./data/fedora/log/apache:/var/log/apache2
    - ./data/fedora/log/tomcat:/usr/local/tomcat/logs



    container_name: isle-fedora

  solr:
    image: islandoracollabgroup/isle-solr:latest
    ports:
      - "8091:8080"
      - "8983:8983"
    tty: true
    volumes:
    - ./customize/solr/tomcat/server.xml:/usr/local/tomcat/conf/server.xml
    - ./customize/solr/tomcat/web.xml:/usr/local/tomcat/conf/web.xml
    - ./customize/solr/tomcat/tomcat-users.xml:/usr/local/tomcat/conf/tomcat-users.xml
    - ./customize/solr/tomcat/logging.properties:/usr/local/tomcat/conf/logging.properties
    - ./data/solr/logs:/usr/local/tomcat/logs
    - ./customize/solr/solr/solr.xml:/usr/local/tomcat/conf/Catalina/localhost/solr.xml
    - ./customize/solr/solr/solrconfig.xml:/usr/local/solr/collection1/conf/solrconfig.xml
    - ./customize/solr/solr/schema.xml:/usr/local/solr/collection1/conf/schema.xml
    - ./customize/solr/solr/log4j.properties:/usr/local/tomcat/webapps/solr/WEB-INF/classes/log4j.properties
    - ./customize/solr/solr/stopwords.txt:/usr/local/solr/collection1/conf/stopwords.txt
    - ./data/solr:/usr/local/solr/collection1/data
    container_name: isle-solr

  apache:
    image: islandoracollabgroup/isle-apache:latest
    environment:
      - JAVA_HOME=/usr/lib/jvm/java-8-oracle/
      - JRE_HOME=/usr/lib/jvm/java-8-oracle/jre
      - PATH="$PATH:$HOME/.composer/vendor/bin:/usr/lib/jvm/java-8-oracle/bin:/usr/lib/jvm/java-8-oracle/jre/bin"
      - KAKADU_LIBRARY_PATH=/opt/adore-djatoka-1.1/lib/Linux-x86-64
      - KAKADU_HOME=/opt/adore-djatoka-1.1/bin/Linux-x86-64
    ports:
      - "80:80"
      - "80:443"
    tty: true
    depends_on:
      - mysql
      - fedora
    volumes:
      - ./customize/apache/apache/site.conf:/etc/apache2/sites-available/site.conf
      - ./customize/apache/site/linux_settings.php:/var/www/html/sites/default/settings.php
      - ./customize/apache/site:/home/islandora/site
      # - ./customize/apache/php/php.ini:/etc/php5/apache2/php.ini #(optional - edit here and remove comment)
      - ./data/apache/drupal:/var/www/html
      - ./data/apache/log/apache:/var/log/apache2
    container_name: isle-apache
