---

- hosts:  isle-prod-project.institution # change this to real host name
  become_user: root
  become_method: sudo

  roles:
    - dependencies
    - users_groups
    - docker
    - docker_compose
    - git_clone
    - docker_images
